import { Router } from "express";
import { optionalAuth, protect, userController } from "./users.legacy-adapters";

const router = Router();

router.get("/", optionalAuth, userController.getUsers);
router.get("/search", optionalAuth, userController.getUsers);
router.post("/create-team", protect, userController.createTeam);
router.get("/avatar/:userId", userController.getAvatar);
router.get("/blocked", protect, userController.getBlockedUsers);
router.post("/block/:username", protect, userController.blockUser);
router.delete("/block/:username", protect, userController.unblockUser);
router.delete("/roster-invite/:inviteId", protect, userController.cancelRosterInvite);
// Player-facing roster invite endpoints (list / accept / decline)
router.get("/roster-invites", protect, userController.getRosterInvites);
router.post("/roster-invites/:inviteId/accept", protect, userController.acceptRosterInvite);
router.post("/roster-invites/:inviteId/decline", protect, userController.declineRosterInvite);
router.delete("/staff-invite/:inviteId", protect, userController.cancelStaffInvite);
router.get("/gaming-stats", protect, userController.getGamingStats);
router.post("/gaming-stats", protect, userController.addGamingStat);
router.put("/gaming-stats/:statId", protect, userController.updateGamingStat);
router.delete("/gaming-stats/:statId", protect, userController.deleteGamingStat);
router.post("/gaming-stats/sync-coc", protect, userController.syncClashOfClansData);
router.post("/gaming-stats/sync-cr", protect, userController.syncClashRoyaleData);
router.get("/:identifier/tournaments", optionalAuth, userController.getLiveTournamentHistory);
router.get("/:username/tournament-history", optionalAuth, userController.getUserTournamentHistory);
router.get("/privacy-settings", protect, userController.getPrivacySettings);
router.put("/privacy-settings", protect, userController.updatePrivacySettings);
router.get("/notification-settings", protect, userController.getNotificationSettings);
router.put("/notification-settings", protect, userController.updateNotificationSettings);
router.get("/:userId/dm-privacy", protect, userController.getDmPrivacy);
router.get("/follow-requests/incoming", protect, userController.getFollowRequests);
router.post("/follow-requests/:requestId/accept", protect, userController.acceptFollowRequest);
router.post("/follow-requests/:requestId/reject", protect, userController.rejectFollowRequest);
router.get("/:identifier", optionalAuth, userController.getUser);
router.post("/:id/follow", protect, userController.toggleFollow);
router.delete("/:id/follow", protect, userController.toggleFollow);
router.get("/:id/followers", optionalAuth, userController.getFollowers);
router.get("/:id/following", optionalAuth, userController.getFollowing);
router.get("/:id/posts", optionalAuth, userController.getUserPosts);
router.get("/:id/clips", optionalAuth, userController.getUserClips);
router.post("/:teamId/roster/add", protect, userController.addPlayerToRoster);
router.delete("/:teamId/roster/:game/leave", protect, userController.leaveTeam);
router.delete("/:teamId/roster/:game/:playerId", protect, userController.removePlayerFromRoster);
router.post("/:teamId/staff/add", protect, userController.addStaffMember);
router.post("/:teamId/staff/add-by-username", protect, userController.addStaffMemberByUsername);
router.delete("/:teamId/staff/:playerId", protect, userController.removeStaffMember);
router.get("/:teamId/pending-invites", protect, userController.getTeamPendingInvites);
router.delete("/:teamId/staff/cancel-by-username", protect, userController.cancelStaffInviteByUsername);
router.post("/:teamId/leave-request", protect, userController.sendLeaveRequest);
router.get("/:teamId/leave-requests", protect, userController.getTeamLeaveRequests);
router.post("/leave-requests/:requestId/approve", protect, userController.approveLeaveRequest);
router.post("/leave-requests/:requestId/reject", protect, userController.rejectLeaveRequest);

export default router;
